name: k6 Load Test
permissions: write-all
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Select the environment to run the test'
        required: true
        default: staging
        type: choice
        options:
          - staging
      scripts:
        description: 'Select the scripts to run'
        required: true
        type: choice
        options:
          - All
          - Admin
          - Landlord
    
  

jobs:
  run-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup K6
        uses: grafana/setup-k6-action@v1
        
      - name: Run all scripts
        if: ${{ github.event.inputs.scripts == 'All' }}
        uses: grafana/run-k6-action@v1
        with:
          path: |
            scripts/Admin/script1.js
            scripts/Landlord/script2.js
          parallel: true

      - name: Run Admin script
        if: ${{ github.event.inputs.scripts == 'Admin' }}
        uses: grafana/run-k6-action@v1
        with:
          path: |
            scripts/Admin/script1.js
          parallel: true

      - name: Run Landlord script
        if: ${{ github.event.inputs.scripts == 'Landlord' }}
        uses: grafana/run-k6-action@v1
        with:
          path: |
            scripts/Landlord/script2.js
          parallel: true

      - name: Upload k6 Test Summary Artifact
        uses: actions/upload-artifact@v3
        with:
          name: k6-summary
          path: csvContent.csv
       
